/*
 * This file is generated by jOOQ.
 */
package com.example.`data`.tables.references




/**
 * The table <code>chat.chat_data</code>.
 */
val CHAT_DATA: com.example.`data`.tables.ChatData = com.example.`data`.tables.ChatData.CHAT_DATA

/**
 * The table <code>chat.chat_room</code>.
 */
val CHAT_ROOM: com.example.`data`.tables.ChatRoom = com.example.`data`.tables.ChatRoom.CHAT_ROOM

/**
 * The table <code>chat.user_chat_rooms</code>.
 */
val USER_CHAT_ROOMS: com.example.`data`.tables.UserChatRooms = com.example.`data`.tables.UserChatRooms.USER_CHAT_ROOMS

/**
 * The table <code>chat.users</code>.
 */
val USERS: com.example.`data`.tables.Users = com.example.`data`.tables.Users.USERS
