/*
 * This file is generated by jOOQ.
 */
package com.example.`data`.indexes


import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val CHAT_DATA_CHAT_ROOM_TIMESTAMP_INDEX: Index = Internal.createIndex(DSL.name("chat_data_chat_room_timestamp_index"), com.example.`data`.tables.ChatData.CHAT_DATA, arrayOf(com.example.`data`.tables.ChatData.CHAT_DATA.CHAT_ROOM, com.example.`data`.tables.ChatData.CHAT_DATA.TIMESTAMP.desc()), false)
