/*
 * This file is generated by jOOQ.
 */
package com.example.`data`


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Chat : SchemaImpl("chat", com.example.`data`.DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>chat</code>
         */
        val CHAT: Chat = Chat()
    }

    /**
     * The table <code>chat.chat_data</code>.
     */
    val CHAT_DATA: com.example.`data`.tables.ChatData get() = com.example.`data`.tables.ChatData.CHAT_DATA

    /**
     * The table <code>chat.chat_room</code>.
     */
    val CHAT_ROOM: com.example.`data`.tables.ChatRoom get() = com.example.`data`.tables.ChatRoom.CHAT_ROOM

    /**
     * The table <code>chat.user_chat_rooms</code>.
     */
    val USER_CHAT_ROOMS: com.example.`data`.tables.UserChatRooms get() = com.example.`data`.tables.UserChatRooms.USER_CHAT_ROOMS

    /**
     * The table <code>chat.users</code>.
     */
    val USERS: com.example.`data`.tables.Users get() = com.example.`data`.tables.Users.USERS

    override fun getCatalog(): Catalog = com.example.`data`.DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        com.example.`data`.tables.ChatData.CHAT_DATA,
        com.example.`data`.tables.ChatRoom.CHAT_ROOM,
        com.example.`data`.tables.UserChatRooms.USER_CHAT_ROOMS,
        com.example.`data`.tables.Users.USERS
    )
}
