/*
 * This file is generated by jOOQ.
 */
package com.example.`data`.tables


import java.time.LocalDateTime
import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ChatData(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, com.example.`data`.tables.records.ChatDataRecord>?,
    aliased: Table<com.example.`data`.tables.records.ChatDataRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<com.example.`data`.tables.records.ChatDataRecord>(
    alias,
    com.example.`data`.Chat.CHAT,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>chat.chat_data</code>
         */
        val CHAT_DATA: ChatData = ChatData()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<com.example.`data`.tables.records.ChatDataRecord> = com.example.`data`.tables.records.ChatDataRecord::class.java

    /**
     * The column <code>chat.chat_data.chat_room</code>.
     */
    val CHAT_ROOM: TableField<com.example.`data`.tables.records.ChatDataRecord, UUID?> = createField(DSL.name("chat_room"), SQLDataType.UUID, this, "")

    /**
     * The column <code>chat.chat_data.timestamp</code>.
     */
    val TIMESTAMP: TableField<com.example.`data`.tables.records.ChatDataRecord, LocalDateTime?> = createField(DSL.name("timestamp"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>chat.chat_data.message</code>.
     */
    val MESSAGE: TableField<com.example.`data`.tables.records.ChatDataRecord, String?> = createField(DSL.name("message"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>chat.chat_data.username</code>.
     */
    val USERNAME: TableField<com.example.`data`.tables.records.ChatDataRecord, String?> = createField(DSL.name("username"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<com.example.`data`.tables.records.ChatDataRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<com.example.`data`.tables.records.ChatDataRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>chat.chat_data</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>chat.chat_data</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>chat.chat_data</code> table reference
     */
    constructor(): this(DSL.name("chat_data"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, com.example.`data`.tables.records.ChatDataRecord>): this(Internal.createPathAlias(child, key), child, key, CHAT_DATA, null)
    override fun getSchema(): Schema? = if (aliased()) null else com.example.`data`.Chat.CHAT
    override fun getIndexes(): List<Index> = listOf(com.example.`data`.indexes.CHAT_DATA_CHAT_ROOM_TIMESTAMP_INDEX)
    override fun `as`(alias: String): ChatData = ChatData(DSL.name(alias), this)
    override fun `as`(alias: Name): ChatData = ChatData(alias, this)
    override fun `as`(alias: Table<*>): ChatData = ChatData(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ChatData = ChatData(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ChatData = ChatData(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ChatData = ChatData(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<UUID?, LocalDateTime?, String?, String?> = super.fieldsRow() as Row4<UUID?, LocalDateTime?, String?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, LocalDateTime?, String?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, LocalDateTime?, String?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
