spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/public
    username: postgres
    password: password1
    pool:
      max-size: 10
      max-idle-time: 30m
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
