/*
 * This file is generated by jOOQ.
 */
package com.example.`data`.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class ChatData(
    var chatRoom: UUID? = null,
    var timestamp: LocalDateTime? = null,
    var message: String? = null,
    var username: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: ChatData = other as ChatData
        if (this.chatRoom == null) {
            if (o.chatRoom != null)
                return false
        }
        else if (this.chatRoom != o.chatRoom)
            return false
        if (this.timestamp == null) {
            if (o.timestamp != null)
                return false
        }
        else if (this.timestamp != o.timestamp)
            return false
        if (this.message == null) {
            if (o.message != null)
                return false
        }
        else if (this.message != o.message)
            return false
        if (this.username == null) {
            if (o.username != null)
                return false
        }
        else if (this.username != o.username)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.chatRoom == null) 0 else this.chatRoom.hashCode())
        result = prime * result + (if (this.timestamp == null) 0 else this.timestamp.hashCode())
        result = prime * result + (if (this.message == null) 0 else this.message.hashCode())
        result = prime * result + (if (this.username == null) 0 else this.username.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("ChatData (")

        sb.append(chatRoom)
        sb.append(", ").append(timestamp)
        sb.append(", ").append(message)
        sb.append(", ").append(username)

        sb.append(")")
        return sb.toString()
    }
}
