/*
 * This file is generated by jOOQ.
 */
package com.example.`data`.tables.pojos


import java.io.Serializable
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class UserChatRooms(
    var userId: String? = null,
    var chatRoomId: UUID? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: UserChatRooms = other as UserChatRooms
        if (this.userId == null) {
            if (o.userId != null)
                return false
        }
        else if (this.userId != o.userId)
            return false
        if (this.chatRoomId == null) {
            if (o.chatRoomId != null)
                return false
        }
        else if (this.chatRoomId != o.chatRoomId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.userId == null) 0 else this.userId.hashCode())
        result = prime * result + (if (this.chatRoomId == null) 0 else this.chatRoomId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("UserChatRooms (")

        sb.append(userId)
        sb.append(", ").append(chatRoomId)

        sb.append(")")
        return sb.toString()
    }
}
