apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chatserver.name }}
spec:
  replicas: {{ .Values.chatserver.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.chatserver.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.chatserver.name }}
    spec:
      containers:
        - name: {{ .Values.chatserver.name }}
          image: {{ .Values.chatserver.image }}
          ports:
            - containerPort: {{ .Values.chatserver.containerPort }}
          env:
            - name: SPRING_R2DBC_URL
              valueFrom:
                secretKeyRef:
                  name: chat-server-secret
                  key: SPRING_R2DBC_URL
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: chat-server-secret
                  key: SPRING_R2DBC_USERNAME
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-server-secret
                  key: SPRING_R2DBC_PASSWORD
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAPSERVERS
              valueFrom:
                secretKeyRef:
                  name: chat-server-secret
                  key: SPRING_KAFKA_CONSUMER_BOOTSTRAPSERVERS

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chatserver.name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: {{ .Values.chatserver.containerPort }}
  selector:
    app: {{ .Values.chatserver.name }}