apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kowl.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kowl.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kowl.name }}
    spec:
      containers:
        - name: {{ .Values.kowl.name }}
          image: {{ .Values.kowl.image }}
          ports:
            - containerPort: {{ .Values.kowl.containerPort }}
          env:
            - name: KAFKA_BROKERS
              value: "{{ .Values.kowl.environment.KAFKA_BROKERS }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kowl.name }}
spec:
  type: {{ .Values.kowl.serviceType }}
  ports:
    - port: 80
      targetPort: {{ .Values.kowl.containerPort }}
  selector:
    app: {{ .Values.kowl.name }}