apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.schemaRegistry.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.schemaRegistry.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.schemaRegistry.serviceName }}
    spec:
      containers:
        - name: {{ .Values.schemaRegistry.name }}
          image: {{ .Values.schemaRegistry.image }}
          ports:
            - containerPort: {{ .Values.schemaRegistry.containerPort }}
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "{{ .Values.schemaRegistry.environment.SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS }}"
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "{{ .Values.schemaRegistry.environment.SCHEMA_REGISTRY_HOST_NAME }}"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "{{ .Values.schemaRegistry.environment.SCHEMA_REGISTRY_LISTENERS }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.schemaRegistry.serviceName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.schemaRegistry.containerPort }}
      targetPort: {{ .Values.schemaRegistry.containerPort }}
  selector:
    app: {{ .Values.schemaRegistry.serviceName }}