apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.timescaledb.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: {{ .Values.timescaledb.containerName }}
          image: {{ .Values.timescaledb.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.timescaledb.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.timescaledb.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.timescaledb.env.POSTGRES_DB }}
            - name: TIMESCALEDB_TELEMETRY
              value: {{ .Values.timescaledb.env.TIMESCALEDB_TELEMETRY }}
            - name: TIMESCALEDB_LICENSE
              value: {{ .Values.timescaledb.env.TIMESCALEDB_LICENSE }}
          ports:
            {{- range .Values.timescaledb.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
                {{- end }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: timescaledb-data
      volumes:
        - name: timescaledb-data
          persistentVolumeClaim:
            claimName: timescaledb-data

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.timescaledb.service.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.timescaledb.service.port }}
      targetPort: {{ .Values.timescaledb.containerPort }}
  selector:
    app: {{ .Values.timescaledb.service.name }}